version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/create-db.sql:/docker-entrypoint-initdb.d/1_create-db.sql
      - ./db/create-table.sql:/docker-entrypoint-initdb.d/2_create-table.sql
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: task_backend
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: tasksdb
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      - db
